//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorSignalRApp.Shared.Hubs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameHubStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameHubStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorSignalRApp.Shared.Hubs.GameHubStrings", typeof(GameHubStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in te zetten.
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht voor GameAdmin om spel te starten.
        /// </summary>
        public static string GameAdminStart {
            get {
                return ResourceManager.GetString("GameAdminStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game gereset. Wacht voor {0} om uit te delen.
        /// </summary>
        public static string GameResetted {
            get {
                return ResourceManager.GetString("GameResetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te spelen.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} heeft gewonnen. Maak tafel leeg.
        /// </summary>
        public static string PlayerWon {
            get {
                return ResourceManager.GetString("PlayerWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht op {0} om {1}.
        /// </summary>
        public static string UserBetted {
            get {
                return ResourceManager.GetString("UserBetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht totdat winnaar is gekozen.
        /// </summary>
        public static string WaitingChooseWinner {
            get {
                return ResourceManager.GetString("WaitingChooseWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht op {0} om kaart te spelen.
        /// </summary>
        public static string WaitingPlayCard {
            get {
                return ResourceManager.GetString("WaitingPlayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht totdat {0} zijn aangemeld.
        /// </summary>
        public static string WaitingSignIn {
            get {
                return ResourceManager.GetString("WaitingSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachten op {0} op in te zetten.
        /// </summary>
        public static string WaitingToBet {
            get {
                return ResourceManager.GetString("WaitingToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht totdat volgende ronde is gestart.
        /// </summary>
        public static string WaitNextRound {
            get {
                return ResourceManager.GetString("WaitNextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht voor {0} om uit te delen.
        /// </summary>
        public static string WaitToShuffle {
            get {
                return ResourceManager.GetString("WaitToShuffle", resourceCulture);
            }
        }
    }
}
